name: tests

on:
  push:
    branches: [ v1.8 ]
  pull_request:
    branches: "*"

jobs:
  build-image:
    name: Build docker image
    runs-on: ubuntu-20.04
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Check out code
        uses: actions/checkout@v3
        with:
          repository: yezzey-gp/gp_modified_for_yezzey
          ref: fix-test-action

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: yezzey:1.0
          accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
          secretAccessKey: ${{ secrets.SECRET_ACCESS_KEY }}
          mockSecret: ${{ secrets.MOCK_SECRET }}
          build-args: |
            accessKeyId=${{secrets.ACCESS_KEY_ID}}
            secretAccessKey=${{secrets.SECRET_ACCESS_KEY}}
            bucketName=test-bucket-yezzey
            yezzeyRef=${{github.ref}}
      - name: Run Docker
        shell: bash
        run: |
          docker run yezzey:1.0

